import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link'

import { Home, Map, User } from "lucide-react";

export const metadata: Metadata = {
  title: "LenzUp",
  description: "Generated by create next app",
  manifest: "/manifest.json"
};

 const NavItem = ({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) => {
  return (
    <Link href={href} className="flex flex-col items-center hover:text-blue-500">
      {icon}
      <span className="text-xs">{label}</span>
    </Link>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="flex flex-col h-screen">
        <header className="fixed top-0 left-0 w-full shadow-md border-b py-3 px-4 flex justify-center items-center z-10">
          <h1 className="text-lg font-bold">LenzUp</h1>
        </header>

        <main className="flex-grow pt-12 pb-16">{children}</main>

        <nav className="fixed bottom-0 left-0 w-full shadow-md border-t flex justify-around py-3">
          <NavItem href="/" icon={<Home size={24} />} label="Accueil" />
          <NavItem href="/map" icon={<Map size={24} />} label="Carte" />
          <NavItem href="/profile" icon={<User size={24} />} label="Profil" />
        </nav>
      </body>
    </html>
  );
}
